const translations = {
    en: {
        "eyebrow": "2x World Champion",
        "hero-label": "Institutional Presentation",
        "hero-desc": "Meet Rodrigo Figueiredo: the only two-time world champion across the industry's leading platforms, with 9 years of professional experience in Binary Options trading.",
        "btn-plans": "View Plans",
        "btn-more": "Learn More",
        "s1-heading": "Headquartered in the world's major financial hubs",
        "loc1-role": "Americas Headquarters",
        "loc2-role": "Asia-Pacific Operations Hub",
        "loc3-role": "New office expanding soon",
        "s4-heading": "Team of high-performance traders",
        "s4-text": "A team many companies want. United by a single mission.",
        "team-jn": "6 years of experience",
        "team-bb": "Team Member",
        "mission-heading": "Transforming Financial Lives",
        "mission-text": "AlphaTrust's mission is to be globally recognized in its field. Join the world's largest community of smart investors.",
        "plans-heading": "Investment Plans",
        "plans-text": "Choose the plan that fits your profile. Capital is returned at the end of all plans.",
        "th-plan": "Plan",
        "th-returns": "Returns",
        "th-duration": "Duration",
        "th-total": "Total Return",
        "th-withdrawal": "Withdrawal Freq.",
        "th-min": "Min.",
        "th-max": "Max.",
        "tag-featured": "Featured",
        "micro-returns": "0.4% per day",
        "micro-duration": "1 day",
        "start-returns": "0.7% per day",
        "start-duration": "7 days",
        "builder-returns": "1.0% per day",
        "builder-duration": "14 days",
        "advance-returns": "1.3% per day",
        "advance-duration": "28 days",
        "pro-returns": "1.6% per day",
        "pro-duration": "56 days",
        "elite-returns": "2.0% per day",
        "elite-duration": "84 days",
        "daily": "Daily",
        "every3": "Every 3 days",
        "every5": "Every 5 days",
        "every7": "Every 7 days",
        "every10": "Every 10 days",
        "activation-title": "AlphaTrust Rules for Activating and Unlocking Levels",
        "activation-subtitle": "Only members with an active package are eligible for residual commissions and network bonuses.",
        "activation-deposit-label": "Minimum deposit",
        "activation-label": "Activation",
        "l1": "Level 1", "l2": "Level 2", "l3": "Level 3", "l4": "Level 4",
        "l5": "Level 5", "l6": "Level 6",
        "commission-title": "Commission Across 6 Levels",
        "levels-note": "Each referral at any level earns you passive income. The structure extends up to 14 levels with diminishing commissions at deeper levels.",
        "withdraw-title": "AlphaTrust Transactions Withdrawals and Fees",
        "withdraw-main": "Automatic transfer",
        "withdraw-sub": "Starting at $0.10",
        "withdraw-desc": "Once your contract has accrued at least $5.00 in earnings, the amount is deposited directly into your Web3 wallet, with no intermediaries.",
        "withdraw-fee-main": "0% Withdrawal Fee",
        "withdraw-fee-sub": "We don't charge you anything based on your success.",
        "withdraw-fee-desc": "100% of your ROI is yours.",
        "vip-title": "AlphaTrust Alpha Experience Career Plan",
        "vip-subtitle": "Climb the career ladder and unlock exclusive rewards",
        "vip-level-1": "Level 1", "vip-level-2": "Level 2", "vip-level-3": "Level 3",
        "vip-level-4": "Level 4", "vip-level-5": "Level 5", "vip-level-6": "Level 6",
        "vip-network-vol": "Network Volume",
        "vip-required": "Required Structure",
        "vip-reward-label": "Reward",
        "vip-one-time": "One-time Payment",
        "vip-vol-1": "$20,000",
        "vip-vol-2": "$80,000",
        "vip-vol-3": "$200,000",
        "vip-vol-4": "$600,000",
        "vip-vol-5": "$1,500,000",
        "vip-vol-6": "$20,000,000",
        "vip-struct-1": "3 Straight Bets at $6,666 Each",
        "vip-struct-2": "3 Straight Bets at $26,666 Each",
        "vip-struct-3": "3 Straight Bets at $66,666 Each",
        "vip-struct-4": "3 Straight Wins, Each Worth $200,000",
        "vip-struct-5": "3 Straight Wins, Each Worth $500,000",
        "vip-struct-6": "3 Straight Bets at $6,666.66 Each",
        "vip-gift-1": "$400",
        "vip-gift-2": "$1,200",
        "vip-gift-3": "iPhone 17 Pro Max + $300/Month",
        "vip-gift-4": "$5,000 + $1,000/Month",
        "vip-gift-5": "$10,000 + $2,500/Month",
        "vip-gift-6": "PORSCHE 718 BOXSTER 0 KM + 2% of Global Sales",
        "earn-direct": "3 Direct Referrals",
        "earn-volume": "$20,000 Volume",
        "asset-dollar": "Dollar",
        "asset-euro": "Euro",
        "asset-oil": "Oil",
        "asset-indices": "Global Indices",
        "earn-title": "Two Ways to Earn",
        "earn-subtitle": "Build your network and unlock multiple income streams",
        "unilevel-title": "Unilevel Plan",
        "unilevel-desc": "Earn commissions from your direct referrals and their network. The more you invest, the more levels you unlock.",
        "direct-ref": "Direct Referral",
        "indirect-ref": "Indirect Referrals (network depth)",
        "unilevel-note": "Your investment determines how many levels you can access",
        "career-title": "Career Plan",
        "career-desc": "Grow through ranks and unlock exclusive rewards. Progress by building a network of 3 direct referrals.",
        "base-req": "Base requirement to start",
        "network-vol": "Network volume to qualify",
        "career-note": "Higher ranks = bigger rewards + monthly income",
        "analytical-title": "Analytical Expertise",
        "analytical-subtitle": "The difference between winning and losing lies in analysis",
        "analytical-text": "Reading a financial chart accurately is a skill that very few people truly master. It requires years of study, thousands of hours of observation, and the ability to identify patterns invisible to the untrained eye.",
        "standards-title": "High-Performance Standards",
        "standards-subtitle": "Identification of Early Movements",
        "advantage-title": "Competitive Advantage",
        "advantage-text": "Rodrigo has reached the top of the world rankings: over 17,000 hours of screen time dedicated exclusively to chart analysis.",
        "advantage-highlight": "It is this analytical intelligence that works for you within AlphaTrust.",
        "binary-title": "Binary Options: The World's Most Dynamic Market",
        "binary-text1": "Imagine having access to a market that moves trillions of dollars a day—the same market traded by major banks, investment funds, and elite professional traders. That's exactly where AlphaTrust comes in.",
        "binary-text2": "Binary options are financial instruments derived from Forex—the world's largest financial market, with a daily trading volume exceeding $7.5 trillion.",
        "binary-compared": "By comparison, the New York Stock Exchange trades about $25 billion a day. Forex is 300 times larger.",
        "global-title": "Global Assets",
        "global-note": "Opportunities arise every minute of the day.",
        "volume-compare": "300x bigger",
        "transparency-title": "Complete Transparency",
        "transparency-subtitle": "Unlike anything you've ever seen",
        "daily-pub-title": "Daily Publications",
        "daily-pub-desc": "Every day, AlphaTrust publishes videos of the trades it has executed—showing the profits earned, unfiltered and with no results hidden. This is a practice that no other company in the industry has ever adopted.",
        "live-streams-title": "Analysis Live Streams",
        "live-streams-desc": "We host daily live streams featuring analysis and live trading in real time. You can watch every decision being made right before your eyes.",
        "mission-title": "Transforming Financial Lives",
        "mission-text": "Through elite analysis, smart investing strategies, and a transparent community that puts your success first.",
        "mission-question": "Your journey to financial freedom starts here.",
        "mission-highlight": "Join the movement and become part of something extraordinary.",
        "mission-cta": "Start Your Journey",
        "mission-badge": "Our Mission",
        "incentive-title": "Structural Incentive Plan",
        "incentive-subtitle": "Commission Distribution",
        "comm-direct": "Level 1 Direct",
        "comm-indirect-2": "Level 02 Indirect",
        "comm-indirect-3": "Level 03 Indirect",
        "comm-indirect-4": "Level 04 Indirect",
        "comm-equalized": "Levels 5–8 Equalized Distributions",
        "comm-depth": "Levels 9–14 Structural Depth",
        "maximize-reach": "Maximize Reach: Our structure is designed to reward both direct sales and the long-term sustainability of the network.",
        "total-commitment": "Total Commitment",
        "level": "Level",
        "commission": "Commission",
        "l1": "Level 1", "l2": "Level 2", "l3": "Level 3", "l4": "Level 4",
        "l5": "Level 5", "l6": "Level 6",
        "l9": "Level 9", "l10": "Level 10", "l11": "Level 11", "l12": "Level 12",
        "l13": "Level 13", "l14": "Level 14",
        "rights": "All rights reserved."
    },
    pt: {
        "eyebrow": "Bicampeão Mundial de Trading",
        "hero-label": "Apresentação Institucional",
        "hero-desc": "Conheça Rodrigo Figueiredo: único bicampeão mundial nas principais plataformas do setor, com 9 anos de experiência profissional em Opções Binárias.",
        "btn-plans": "Ver Planos",
        "btn-more": "Saiba Mais",
        "s1-heading": "Sede nos principais centros financeiros mundiais",
        "loc1-role": "Sede das Américas",
        "loc2-role": "Hub Asiático de Operações",
        "loc3-role": "Novo escritório em expansão",
        "s4-heading": "Time de traders de alta competência",
        "s4-text": "Um time desejado por muitas empresas. Reunido em uma só missão.",
        "team-jn": "6 anos de experiência",
        "team-bb": "Membro da Equipe",
        "mission-heading": "Transformando Vidas Financeiras",
        "mission-text": "A missão da AlphaTrust é ser reconhecida mundialmente. Faça parte da maior comunidade de investidores inteligentes do mundo.",
        "plans-heading": "Planos de Investimento",
        "plans-text": "Escolha o plano ideal para o seu perfil. Capital devolvido ao final em todos os planos.",
        "th-plan": "Plano",
        "th-returns": "Rentabilidade",
        "th-duration": "Duração",
        "th-total": "Retorno Total",
        "th-withdrawal": "Frequência Saque",
        "th-min": "Mín.",
        "th-max": "Máx.",
        "tag-featured": "Destaque",
        "micro-returns": "0,4% ao dia",
        "micro-duration": "1 dia",
        "start-returns": "0,7% ao dia",
        "start-duration": "7 dias",
        "builder-returns": "1,0% ao dia",
        "builder-duration": "14 dias",
        "advance-returns": "1,3% ao dia",
        "advance-duration": "28 dias",
        "pro-returns": "1,6% ao dia",
        "pro-duration": "56 dias",
        "elite-returns": "2,0% ao dia",
        "elite-duration": "84 dias",
        "daily": "Diário",
        "every3": "A cada 3 dias",
        "every5": "A cada 5 dias",
        "every7": "A cada 7 dias",
        "every10": "A cada 10 dias",
        "activation-title": "AlphaTrust Regras para Ativação e Desbloqueio de Níveis",
        "activation-subtitle": "Apenas membros com pacote ativo são elegíveis para comissões residuais e bônus de rede.",
        "activation-deposit-label": "Depósito mínimo",
        "activation-label": "Ativação",
        "l1": "Nível 1", "l2": "Nível 2", "l3": "Nível 3", "l4": "Nível 4",
        "l5": "Nível 5", "l6": "Nível 6",
        "commission-title": "Comissão em 6 Níveis",
        "levels-note": "Cada indicação em qualquer nível gera renda passiva. A estrutura se estende até 14 níveis com comissões decrescentes em níveis mais profundos.",
        "withdraw-title": "AlphaTrust Transações Saques e Taxas",
        "withdraw-main": "Transferência automática",
        "withdraw-sub": "A partir de $0.10",
        "withdraw-desc": "Assim que seu contrato acumular pelo menos $5.00 em ganhos, o valor é depositado diretamente na sua carteira Web3, sem intermediários.",
        "withdraw-fee-main": "0% Taxa de Saque",
        "withdraw-fee-sub": "Não cobramos nada baseado no seu sucesso.",
        "withdraw-fee-desc": "100% do seu ROI é seu.",
        "vip-title": "AlphaTrust Alpha Experience Plano de Carreira",
        "vip-subtitle": "Suba na carreira e desbloqueie recompensas exclusivas",
        "vip-level-1": "Nível 1", "vip-level-2": "Nível 2", "vip-level-3": "Nível 3",
        "vip-level-4": "Nível 4", "vip-level-5": "Nível 5", "vip-level-6": "Nível 6",
        "vip-network-vol": "Volume de Rede",
        "vip-required": "Estrutura Requerida",
        "vip-reward-label": "Recompensa",
        "vip-vol-1": "$20,000",
        "vip-vol-2": "$80,000",
        "vip-vol-3": "$200,000",
        "vip-vol-4": "$600,000",
        "vip-vol-5": "$1,500,000",
        "vip-vol-6": "$20,000,000",
        "vip-struct-1": "3 Apostas Diretas de $6,666 Cada",
        "vip-struct-2": "3 Apostas Diretas de $26,666 Cada",
        "vip-struct-3": "3 Apostas Diretas de $66,666 Cada",
        "vip-struct-4": "3 Vitórias Diretas de $200,000 Cada",
        "vip-struct-5": "3 Vitórias Diretas de $500,000 Cada",
        "vip-struct-6": "3 Apostas Diretas de $6,666.66 Cada",
        "vip-gift-1": "$400",
        "vip-gift-2": "$1,200",
        "vip-gift-3": "iPhone 17 Pro Max + $300/Mês",
        "vip-gift-4": "$5,000 + $1,000/Mês",
        "vip-gift-5": "$10,000 + $2,500/Mês",
        "vip-gift-6": "PORSCHE 718 BOXSTER 0 KM + 2% das Vendas Globais",
        "vip-one-time": "Pagamento Único",
        "earn-direct": "3 Indicados Diretos",
        "earn-volume": "Volume de $20,000",
        "asset-dollar": "Dólar",
        "asset-euro": "Euro",
        "asset-oil": "Petróleo",
        "asset-indices": "Índices Globais",
        "earn-title": "Duas Formas de Ganhar",
        "earn-subtitle": "Construa sua rede e desbloqueie múltiplas fontes de renda",
        "unilevel-title": "Plano Unilevel",
        "unilevel-desc": "Ganhe comissões dos seus indicados diretos e da rede deles. Quanto mais você investe, mais níveis desbloqueia.",
        "direct-ref": "Indicado Direto",
        "indirect-ref": "Indicados Indiretos (profundidade de rede)",
        "unilevel-note": "Seu investimento determina quantos níveis você pode acessar",
        "career-title": "Plano de Carreira",
        "career-desc": "Cresça através de patentes e desbloqueie recompensas exclusivas. Progredindo com uma rede de 3 indicados diretos.",
        "base-req": "Requisito base para começar",
        "network-vol": "Volume de rede para qualificar",
        "career-note": "Patentes mais altas = maiores recompensas + renda mensal",
        "analytical-title": "Expertise Analítica",
        "analytical-subtitle": "A diferença entre vencer e perder está na análise",
        "analytical-text": "Ler um gráfico financeiro com precisão é uma habilidade que poucas pessoas realmente dominam. Requer anos de estudo, milhares de horas de observação e a capacidade de identificar padrões invisíveis ao olho não treinado.",
        "standards-title": "Padrões de Alto Desempenho",
        "standards-subtitle": "Identificação de Movimentos Antecipados",
        "advantage-title": "Vantagem Competitiva",
        "advantage-text": "Rodrigo alcançou o topo do ranking mundial: mais de 17.000 horas de tempo de tela dedicadas exclusivamente à análise de gráficos.",
        "advantage-highlight": "É essa inteligência analítica que trabalha para você dentro da AlphaTrust.",
        "binary-title": "Opções Binárias: O Mercado Mais Dinâmico do Mundo",
        "binary-text1": "Imagine ter acesso a um mercado que move trilhões de dólares por dia — o mesmo mercado negociado por grandes bancos, fundos de investimento e traders profissionais de elite. É exatamente aí que a AlphaTrust entra.",
        "binary-text2": "Opções binárias são instrumentos financeiros derivados do Forex — o maior mercado financeiro do mundo, com volume de negociação diário superior a $7.5 trilhões.",
        "binary-compared": "Para comparação, a Bolsa de Nova York negocia cerca de $25 bilhões por dia. O Forex é 300 vezes maior.",
        "global-title": "Ativos Globais",
        "global-note": "Oportunidades surgem a cada minuto do dia.",
        "volume-compare": "300x maior",
        "transparency-title": "Transparência Completa",
        "transparency-subtitle": "Diferente de tudo que você já viu",
        "daily-pub-title": "Publicações Diárias",
        "daily-pub-desc": "Todos os dias, a AlphaTrust publica vídeos das operações executadas — mostrando os lucros obtidos, sem filtro e sem resultados escondidos. Esta é uma prática que nenhuma outra empresa do setor jamais adotou.",
        "live-streams-title": "Lives de Análise",
        "live-streams-desc": "Realizamos lives diárias com análises e operações em tempo real. Você pode assistir cada decisão sendo tomada bem diante dos seus olhos.",
        "mission-heading": "Transformando Vidas Financeiras",
        "mission-text": "A missão da AlphaTrust é ser reconhecida mundialmente. Faça parte da maior comunidade de investidores inteligentes do mundo.",
        "mission-question": "Sua jornada para a liberdade financeira começa aqui.",
        "mission-highlight": "Junte-se ao movimento e faça parte de algo extraordinário.",
        "mission-cta": "Comece Sua Jornada",
        "mission-badge": "Nossa Missão",
        "incentive-title": "Plano de Incentivo Estrutural",
        "incentive-subtitle": "Distribuição de Comissões",
        "comm-direct": "Nível 1 Direto",
        "comm-indirect-2": "Nível 02 Indireto",
        "comm-indirect-3": "Nível 03 Indireto",
        "comm-indirect-4": "Nível 04 Indireto",
        "comm-equalized": "Níveis 5–8 Distribuições Equalizadas",
        "comm-depth": "Níveis 9–14 Profundidade Estrutural",
        "maximize-reach": "Maximizar Alcance: Nossa estrutura foi projetada para recompensar tanto vendas diretas quanto a sustentabilidade de longo prazo da rede.",
        "total-commitment": "Compromisso Total",
        "level": "Nível",
        "commission": "Comissão",
        "l1": "Nível 1", "l2": "Nível 2", "l3": "Nível 3", "l4": "Nível 4",
        "l5": "Nível 5", "l6": "Nível 6", "l7": "Nível 7", "l8": "Nível 8",
        "l9": "Nível 9", "l10": "Nível 10", "l11": "Nível 11", "l12": "Nível 12",
        "l13": "Nível 13", "l14": "Nível 14",
        "rights": "Todos os direitos reservados."
    }
};

let currentLang = 'en';

function setLanguage(lang) {
    currentLang = lang;
    document.documentElement.lang = lang;

    document.querySelectorAll('[data-i18n]').forEach(el => {
        const key = el.getAttribute('data-i18n');
        if (translations[lang][key]) {
            el.textContent = translations[lang][key];
        }
    });

    document.querySelectorAll('.lang-btn').forEach(btn => {
        btn.classList.toggle('active', btn.dataset.lang === lang);
    });

    localStorage.setItem('alpha-lang', lang);
}

document.querySelectorAll('.lang-btn').forEach(btn => {
    btn.addEventListener('click', () => setLanguage(btn.dataset.lang));
});

const savedLang = localStorage.getItem('alpha-lang');
if (savedLang) {
    setLanguage(savedLang);
}

let lastScroll = 0;
const navbar = document.querySelector('.navbar');

window.addEventListener('scroll', () => {
    const currentScroll = window.pageYOffset;
    
    if (currentScroll > 100) {
        if (currentScroll > lastScroll) {
            navbar.classList.add('hidden');
        } else {
            navbar.classList.remove('hidden');
        }
    } else {
        navbar.classList.remove('hidden');
    }
    
    lastScroll = currentScroll;
});