const translations = {
    en: {
        "eyebrow": "2x World Champion",
        "hero-label": "Institutional Presentation",
        "hero-desc": "Meet Rodrigo Figueiredo: the only two-time world champion across the industry's leading platforms, with 9 years of professional experience in Binary Options trading.",
        "btn-plans": "View Plans",
        "btn-more": "Learn More",
        "s1-heading": "Headquartered in the world's major financial hubs",
        "loc1-role": "Americas Headquarters — gateway to North and South American markets",
        "loc2-role": "Asia-Pacific Hub — 24-hour market coverage across Tokyo, Hong Kong, Sydney",
        "loc3-role": "New operations center — expanding 2026",
        "s4-heading": "Team of high-performance traders",
        "s4-text": "A team many companies want. United by a single mission.",
        "team-rf": "Founder & CEO — 2x World Champion",
        "team-jn": "Asian Markets Specialist — 6 years of experience",
        "team-jt": "Trading Analyst",
        "team-bb": "Client Relations",
        "mission-heading": "Transforming Financial Lives",
        "mission-text": "AlphaTrust's mission is to be globally recognized in its field. Join the world's largest community of smart investors.",
        "plans-heading": "Investment Plans",
        "plans-text": "Choose the plan that fits your profile. Capital is returned at the end of all plans.",
        "th-plan": "Plan",
        "th-returns": "Returns",
        "th-duration": "Duration",
        "th-total": "Total Return",
        "th-withdrawal": "Withdrawal Freq.",
        "th-min": "Min.",
        "th-max": "Max.",
        "tag-featured": "Featured",
        "micro-returns": "0.4% per day",
        "micro-duration": "1 day",
        "start-returns": "0.7% per day",
        "start-duration": "7 days",
        "builder-returns": "1.0% per day",
        "builder-duration": "14 days",
        "advance-returns": "1.3% per day",
        "advance-duration": "28 days",
        "pro-returns": "1.6% per day",
        "pro-duration": "56 days",
        "elite-returns": "2.0% per day",
        "elite-duration": "84 days",
        "daily": "Daily",
        "every3": "Every 3 days",
        "every5": "Every 5 days",
        "every7": "Every 7 days",
        "every10": "Every 10 days",
        "activation-title": "Rules for Activating and Unlocking Levels",
        "activation-subtitle": "Only members with an active package are eligible for residual commissions and network bonuses.",
        "activation-deposit-label": "Minimum deposit",
        "activation-label": "Activation",
        "l1": "Level 1", "l2": "Level 2", "l3": "Level 3", "l4": "Level 4",
        "l5": "Level 5", "l6": "Level 6",
        "commission-title": "Commission Structure",
        "levels-note": "Each referral at any level earns you passive income. The structure extends up to 14 levels.",
        "levels-deep-header": "Levels 7–14 Commission Range",
        "deep-label-1": "Levels 7–9",
        "deep-label-2": "Levels 10–12",
        "deep-label-3": "Levels 13–14",
        "withdraw-title": "Transactions Withdrawals and Fees",
        "withdraw-main": "Automatic transfer",
        "withdraw-sub": "Starting at $0.10",
        "withdraw-desc": "Once your contract has accrued at least $5.00 in earnings, the amount is deposited directly into your Web3 wallet, with no intermediaries.",
        "withdraw-fee-main": "0% Withdrawal Fee",
        "withdraw-fee-sub": "We don't charge you anything based on your success.",
        "withdraw-fee-desc": "100% of your ROI is yours.",
        "vip-title": "AlphaTrust Alpha Experience Career Plan",
        "vip-subtitle": "Climb the career ladder and unlock exclusive rewards",
        "vip-level-1": "Level 1", "vip-level-2": "Level 2", "vip-level-3": "Level 3",
        "vip-level-4": "Level 4", "vip-level-5": "Level 5", "vip-level-6": "Level 6",
        "vip-network-vol": "Network Volume",
        "vip-required": "Required Structure",
        "vip-reward-label": "Reward",
        "vip-one-time": "One-time Payment",
        "vip-vol-1": "$20,000",
        "vip-vol-2": "$80,000",
        "vip-vol-3": "$200,000",
        "vip-vol-4": "$600,000",
        "vip-vol-5": "$1,500,000",
        "vip-vol-6": "$20,000,000",
        "vip-struct-1": "3 Straight Bets at $6,666 Each",
        "vip-struct-2": "3 Straight Bets at $26,666 Each",
        "vip-struct-3": "3 Straight Bets at $66,666 Each",
        "vip-struct-4": "3 Straight Wins, Each Worth $200,000",
        "vip-struct-5": "3 Straight Wins, Each Worth $500,000",
        "vip-struct-6": "3 Straight Bets at $6,666.66 Each",
        "vip-gift-1": "$400",
        "vip-gift-2": "$1,200",
        "vip-gift-3": "iPhone 17 Pro Max + $300/Month (12 months)",
        "vip-gift-4": "$5,000 + $1,000/Month (12 months)",
        "vip-gift-5": "$10,000 + $2,500/Month (12 months)",
        "vip-gift-6": "PORSCHE 718 BOXSTER 0 KM + 2% of Monthly Global Sales (Lifetime)",
        "earn-direct": "3 Direct Referrals",
        "earn-volume": "$20,000 Volume",
        "asset-dollar": "Dollar",
        "asset-euro": "Euro",
        "asset-oil": "Oil",
        "asset-indices": "Global Indices",
        "earn-title": "Two Ways to Earn",
        "earn-subtitle": "Two complementary systems — passive income from your network AND monthly rewards from career growth",
        "unilevel-title": "Unilevel Plan",
        "unilevel-desc": "Earn passive income from every referral at every level they participate. Your deposit directly determines how deep your commissions reach — from Level 1 to Level 14.",
        "direct-ref": "Direct Referral",
        "indirect-ref": "Indirect Referrals (network depth)",
        "unilevel-note": "The higher your deposit, the more levels you unlock",
        "career-title": "Career Plan",
        "career-desc": "Climb the rank ladder by building a team of 3 direct referrals and qualifying network volume. Each rank unlocks tangible rewards and a monthly income stream.",
        "base-req": "3 Direct Referrals",
        "network-vol": "$20,000 Network Volume",
        "career-note": "Career rewards are cumulative — the higher your rank, the greater your monthly percentage of global sales",
        "analytical-title": "Analytical Expertise",
        "analytical-subtitle": "Deep market analysis across multiple timeframes",
        "analytical-text": "Our team combines technical analysis, price action, and macro fundamentals to identify high-probability setups across currencies, commodities, and indices. Every signal is cross-referenced across multiple indicators before execution.",
        "standards-title": "High-Performance Standards",
        "standards-subtitle": "Identification of Early Movements",
        "advantage-title": "Competitive Advantage",
        "advantage-text": "Rodrigo has reached the top of the world rankings: over 17,000 hours of screen time dedicated exclusively to chart analysis.",
        "advantage-highlight": "It is this analytical intelligence that works for you within AlphaTrust.",
        "binary-title": "Binary Options: The World's Most Dynamic Market",
        "binary-text1": "Binary Options allow you to profit from the directional movement of assets — currencies, commodities, and global indices — across the world's largest financial market.",
        "binary-text2": "The Forex market moves over $7.5 trillion every single day. That's the same market traded by major banks, hedge funds, and professional traders worldwide.",
        "binary-compared": "For context: the New York Stock Exchange handles about $25 billion daily — making Forex 300 times larger.",
        "global-title": "Global Assets",
        "global-note": "Opportunities arise every minute of the day.",
        "volume-compare": "300x bigger",
        "transparency-title": "Complete Transparency",
        "transparency-subtitle": "Unlike anything you've ever seen",
        "daily-pub-title": "Daily Publications",
        "daily-pub-desc": "Every day, AlphaTrust publishes videos of the trades it has executed—showing the profits earned, unfiltered and with no results hidden. This is a practice that no other company in the industry has ever adopted.",
        "live-streams-title": "Analysis Live Streams",
        "live-streams-desc": "We host daily live streams featuring analysis and live trading in real time. You can watch every decision being made right before your eyes.",
        "mission-question": "Your journey to financial freedom starts here.",
        "mission-highlight": "Join the movement and become part of something extraordinary.",
        "mission-cta": "Start Your Journey",
        "mission-badge": "Our Mission",
        "l1": "Level 1", "l2": "Level 2", "l3": "Level 3", "l4": "Level 4",
        "l5": "Level 5", "l6": "Level 6",
        "l7": "Level 7", "l8": "Level 8", "l9": "Level 9", "l10": "Level 10",
        "l11": "Level 11", "l12": "Level 12", "l13": "Level 13", "l14": "Level 14",
        "guide-start": "New to investing?",
        "guide-start-desc": "Start with MICRO to test the platform with minimal risk.",
        "guide-steady": "Looking for steady income?",
        "guide-steady-desc": "BUILDER and ADVANCE offer strong daily returns with compounding potential.",
        "guide-max": "Maximize returns?",
        "guide-max-desc": "ELITE delivers the highest daily rate with long-term compounding.",
        "cta-title": "Ready to Get Started?",
        "cta-text": "Join AlphaTrust today and start your journey with a platform that prioritizes transparency, security, and results.",
        "cta-button": "Open Your Account",
        "rights": "All rights reserved."
    },
    pt: {
        "eyebrow": "Bicampeão Mundial de Trading",
        "hero-label": "Apresentação Institucional",
        "hero-desc": "Conheça Rodrigo Figueiredo: único bicampeão mundial nas principais plataformas do setor, com 9 anos de experiência profissional em Opções Binárias.",
        "btn-plans": "Ver Planos",
        "btn-more": "Saiba Mais",
        "s1-heading": "Sede nos principais centros financeiros mundiais",
        "loc1-role": "Sede das Américas — porta de entrada para os mercados norte e sul-americanos",
        "loc2-role": "Hub Ásia-Pacífico — cobertura 24h nos mercados de Tóquio, Hong Kong e Sidney",
        "loc3-role": "Novo centro de operações — expansão em 2026",
        "s4-heading": "Time de traders de alta competência",
        "s4-text": "Um time desejado por muitas empresas. Reunido em uma só missão.",
        "team-rf": "Founder & CEO — Bicampeão Mundial",
        "team-jn": "Especialista em Mercados Asiáticos — 6 anos de experiência",
        "team-jt": "Analista de Trading",
        "team-bb": "Relações com Clientes",
        "mission-heading": "Transformando Vidas Financeiras",
        "mission-text": "A missão da AlphaTrust é ser reconhecida mundialmente. Faça parte da maior comunidade de investidores inteligentes do mundo.",
        "plans-heading": "Planos de Investimento",
        "plans-text": "Escolha o plano ideal para o seu perfil. Capital devolvido ao final em todos os planos.",
        "th-plan": "Plano",
        "th-returns": "Rentabilidade",
        "th-duration": "Duração",
        "th-total": "Retorno Total",
        "th-withdrawal": "Frequência Saque",
        "th-min": "Mín.",
        "th-max": "Máx.",
        "tag-featured": "Destaque",
        "micro-returns": "0,4% ao dia",
        "micro-duration": "1 dia",
        "start-returns": "0,7% ao dia",
        "start-duration": "7 dias",
        "builder-returns": "1,0% ao dia",
        "builder-duration": "14 dias",
        "advance-returns": "1,3% ao dia",
        "advance-duration": "28 dias",
        "pro-returns": "1,6% ao dia",
        "pro-duration": "56 dias",
        "elite-returns": "2,0% ao dia",
        "elite-duration": "84 dias",
        "daily": "Diário",
        "every3": "A cada 3 dias",
        "every5": "A cada 5 dias",
        "every7": "A cada 7 dias",
        "every10": "A cada 10 dias",
        "activation-title": "Regras para Ativação e Desbloqueio de Níveis",
        "activation-subtitle": "Apenas membros com pacote ativo são elegíveis para comissões residuais e bônus de rede.",
        "activation-deposit-label": "Depósito mínimo",
        "activation-label": "Ativação",
        "l1": "Nível 1", "l2": "Nível 2", "l3": "Nível 3", "l4": "Nível 4",
        "l5": "Nível 5", "l6": "Nível 6",
        "commission-title": "Estrutura de Comissão",
        "levels-note": "Cada indicação em qualquer nível gera renda passiva. A estrutura se estende até 14 níveis.",
        "levels-deep-header": "Faixa de Comissão dos Níveis 7–14",
        "deep-label-1": "Níveis 7–9",
        "deep-label-2": "Níveis 10–12",
        "deep-label-3": "Níveis 13–14",
        "withdraw-title": "Transações Saques e Taxas",
        "withdraw-main": "Transferência automática",
        "withdraw-sub": "A partir de $0.10",
        "withdraw-desc": "Assim que seu contrato acumular pelo menos $5.00 em ganhos, o valor é depositado diretamente na sua carteira Web3, sem intermediários.",
        "withdraw-fee-main": "0% Taxa de Saque",
        "withdraw-fee-sub": "Não cobramos nada baseado no seu sucesso.",
        "withdraw-fee-desc": "100% do seu ROI é seu.",
        "vip-title": "AlphaTrust Alpha Experience Plano de Carreira",
        "vip-subtitle": "Suba na carreira e desbloqueie recompensas exclusivas",
        "vip-level-1": "Nível 1", "vip-level-2": "Nível 2", "vip-level-3": "Nível 3",
        "vip-level-4": "Nível 4", "vip-level-5": "Nível 5", "vip-level-6": "Nível 6",
        "vip-network-vol": "Volume de Rede",
        "vip-required": "Estrutura Requerida",
        "vip-reward-label": "Recompensa",
        "vip-vol-1": "$20,000",
        "vip-vol-2": "$80,000",
        "vip-vol-3": "$200,000",
        "vip-vol-4": "$600,000",
        "vip-vol-5": "$1,500,000",
        "vip-vol-6": "$20,000,000",
        "vip-struct-1": "3 Apostas Diretas de $6,666 Cada",
        "vip-struct-2": "3 Apostas Diretas de $26,666 Cada",
        "vip-struct-3": "3 Apostas Diretas de $66,666 Cada",
        "vip-struct-4": "3 Vitórias Diretas de $200,000 Cada",
        "vip-struct-5": "3 Vitórias Diretas de $500,000 Cada",
        "vip-struct-6": "3 Apostas Diretas de $6,666.66 Cada",
        "vip-gift-1": "$400",
        "vip-gift-2": "$1,200",
        "vip-gift-3": "iPhone 17 Pro Max + $300/Mês (12 meses)",
        "vip-gift-4": "$5,000 + $1,000/Mês (12 meses)",
        "vip-gift-5": "$10,000 + $2,500/Mês (12 meses)",
        "vip-gift-6": "PORSCHE 718 BOXSTER 0 KM + 2% das Vendas Globais Mensais (Vitalício)",
        "vip-one-time": "Pagamento Único",
        "earn-direct": "3 Indicados Diretos",
        "earn-volume": "Volume de $20,000",
        "asset-dollar": "Dólar",
        "asset-euro": "Euro",
        "asset-oil": "Petróleo",
        "asset-indices": "Índices Globais",
        "earn-title": "Duas Formas de Ganhar",
        "earn-subtitle": "Dois sistemas complementares — renda passiva da sua rede E recompensas mensais de carreira",
        "unilevel-title": "Plano Unilevel",
        "unilevel-desc": "Ganhe renda passiva de cada indicado em cada nível em que ele participa. Seu depósito determina diretamente a profundidade das suas comissões — do Nível 1 ao Nível 14.",
        "direct-ref": "Indicado Direto",
        "indirect-ref": "Indicados Indiretos (profundidade de rede)",
        "unilevel-note": "Quanto maior seu depósito, mais níveis você desbloqueia",
        "career-title": "Plano de Carreira",
        "career-desc": "Suba na hierarquia construindo uma equipe de 3 indicados diretos e atingir volume de rede qualificado. Cada patente desbloqueia recompensas tangíveis e uma renda mensal.",
        "base-req": "3 Indicados Diretos",
        "network-vol": "$20,000 Volume de Rede",
        "career-note": "Recompensas de carreira são cumulativas — quanto maior sua patente, maior seu percentual mensal das vendas globais",
        "analytical-title": "Expertise Analítica",
        "analytical-subtitle": "Análise profunda de mercado em múltiplos timeframes",
        "analytical-text": "Nossa equipe combina análise técnica, price action e fundamentos macroeconômicos para identificar operações de alta probabilidade em moedas, commodities e índices. Cada sinal é cross-referenciado entre múltiplos indicadores antes da execução.",
        "standards-title": "Padrões de Alto Desempenho",
        "standards-subtitle": "Identificação de Movimentos Antecipados",
        "advantage-title": "Vantagem Competitiva",
        "advantage-text": "Rodrigo alcançou o topo do ranking mundial: mais de 17.000 horas de tempo de tela dedicadas exclusivamente à análise de gráficos.",
        "advantage-highlight": "É essa inteligência analítica que trabalha para você dentro da AlphaTrust.",
        "binary-title": "Opções Binárias: O Mercado Mais Dinâmico do Mundo",
        "binary-text1": "Opções Binárias permitem lucrar com o movimento direcional de ativos — moedas, commodities e índices globais — no maior mercado financeiro do mundo.",
        "binary-text2": "O mercado Forex move mais de $7.5 trilhões por dia. É o mesmo mercado negociado por grandes bancos, fundos de hedge e traders profissionais em todo o mundo.",
        "binary-compared": "Como referência: a Bolsa de Nova York negocia cerca de $25 bilhões por dia — tornando o Forex 300 vezes maior.",
        "global-title": "Ativos Globais",
        "global-note": "Oportunidades surgem a cada minuto do dia.",
        "volume-compare": "300x maior",
        "transparency-title": "Transparência Completa",
        "transparency-subtitle": "Diferente de tudo que você já viu",
        "daily-pub-title": "Publicações Diárias",
        "daily-pub-desc": "Todos os dias, a AlphaTrust publica vídeos das operações executadas — mostrando os lucros obtidos, sem filtro e sem resultados escondidos. Esta é uma prática que nenhuma outra empresa do setor jamais adotou.",
        "live-streams-title": "Lives de Análise",
        "live-streams-desc": "Realizamos lives diárias com análises e operações em tempo real. Você pode assistir cada decisão sendo tomada bem diante dos seus olhos.",
        "mission-question": "Sua jornada para a liberdade financeira começa aqui.",
        "mission-highlight": "Junte-se ao movimento e faça parte de algo extraordinário.",
        "mission-cta": "Comece Sua Jornada",
        "mission-badge": "Nossa Missão",
        "guide-start": "Começando a investir?",
        "guide-start-desc": "Comece pelo MICRO para testar a plataforma com risco mínimo.",
        "guide-steady": "Buscando renda fixa?",
        "guide-steady-desc": "BUILDER e ADVANCE oferecem retornos diários sólidos com potencial de juros compostos.",
        "guide-max": "Maximizar retornos?",
        "guide-max-desc": "ELITE entrega a maior taxa diária com potencial de composição a longo prazo.",
        "cta-title": "Pronto para Começar?",
        "cta-text": "Junte-se à AlphaTrust hoje e inicie sua jornada com uma plataforma que prioriza transparência, segurança e resultados.",
        "cta-button": "Abra Sua Conta",
        "rights": "Todos os direitos reservados."
    }
};

let currentLang = 'en';

function setLanguage(lang) {
    currentLang = lang;
    document.documentElement.lang = lang;

    document.querySelectorAll('[data-i18n]').forEach(el => {
        const key = el.getAttribute('data-i18n');
        if (translations[lang][key]) {
            el.textContent = translations[lang][key];
        }
    });

    document.querySelectorAll('.lang-btn').forEach(btn => {
        btn.classList.toggle('active', btn.dataset.lang === lang);
    });

    localStorage.setItem('alpha-lang', lang);
}

document.querySelectorAll('.lang-btn').forEach(btn => {
    btn.addEventListener('click', () => setLanguage(btn.dataset.lang));
});

const savedLang = localStorage.getItem('alpha-lang');
if (savedLang) {
    setLanguage(savedLang);
}

let lastScroll = 0;
const navbar = document.querySelector('.navbar');

window.addEventListener('scroll', () => {
    const currentScroll = window.pageYOffset;
    
    if (currentScroll > 100) {
        if (currentScroll > lastScroll) {
            navbar.classList.add('hidden');
        } else {
            navbar.classList.remove('hidden');
        }
    } else {
        navbar.classList.remove('hidden');
    }
    
    lastScroll = currentScroll;
});